test/test_graftm.py
This is just the failing test, not the fix for it, I'm afraid.
=> add failing hit for multiple hits in the same contig

graftm/hmmer.py
=> remove comment

bin/graftM, graftm/housekeeping.py, test/test_graftm.py
Use spaces not commas to be consistent with --search_hmm_files, and to be more pythonesque
=> Use space separation rather than comma separation for fowrd and rev inputs

graftm/hmmer.py, graftm/run.py, graftm/unpack_sequences.py
Seems to pass all the tests, but do you mind suggesting some English for the `?` bits in some of the method documentation please?
=> make lower-level methods for nt_db_search and aa_db_search

bin/graftM, graftm/bootstrapper.py, graftm/hmmer.py, graftm/housekeeping.py, graftm/run.py, test/test_bootstrapper.py
Incidentally, I also removed `default=argparse.SUPPRESS` from a graft option, and fixed a bug that happened when maximum_range was `None`.
If you are happy with these changes then go ahead and merge.
ta.
=> add bootstrap mode

test/test_summarise.py
in response to your email about this.
=> use tempfiles more in biom testing

bin/graftM, graftm/create.py, graftm/run.py, test/test_create.py
small fixes for create. Merge if you like - ta.
=> Less create output

graftm/run.py
=> bugfix: when hmmsearch hits but diamond has no hits, assign to Root

graftm/diamond.py, graftm/graftm_output_paths.py, graftm/hmmer.py, graftm/run.py, test/test_diamond.py, test/test_graft.py
keeping the diamond and hmmsearch outputs now
=> Less removing

graftm/create.py
Hey I wasn't able to test these (minor) changes, because create tests were failing elsewhere - I imagine you're already on it.
ta
=> create: find errors in taxonomy specification before tree building

graftm/create.py, graftm/graftm_package.py, test/test_graftm_package.py
Hey a pull request after #126 just to make things a little less hacky. Untested still since the base branch doesn't pass the tests. A simple method though.
=> Refpkg tree path

graftm/create.py
hey Joel can you write a test or two for the dereplication code please? I imagine this pull request is pretty harmless, but would be good to know.
Thanks.
=> make dereplication code less specific to genus-dereplication

graftm/create.py, graftm/getaxnseq.py, test/test_getaxnseq.py
further to #135 
this isn't a perfect solution, it would be better to be able to define >7 levels, but eh for now.
=> More gettaxnseq levels

bin/graftM, graftm/create.py, graftm/decorator.py, graftm/getaxnseq.py, graftm/run.py, graftm/tree_decorator.py, test/test_getaxnseq.py
=> Rename decorate to tree

graftm/create.py
seems there's a lot of whitespace change, you can ignore this by adding "?w=1" to the URL of this pull request, I think.
=> create: allow incomplete taxa strings when dereplicating, plus doco fix

bin/graftM, graftm/create.py, graftm/getaxnseq.py, graftm/greengenes_taxonomy.py, graftm/tree_decorator.py, test/test_greengenes_taxonomy.py
further to #138 this just cleans up the code a bit - previously reading greengenes style taxonomy files were done in two places (maybe more?) - here I've abstracted it out and added tests.
Now we are at 99 tests!
```
$ nosetests -x
...................................................................................................
----------------------------------------------------------------------
Ran 99 tests in 218.503s
OK
```
=> DRY taxonomy reading

README.md
Just changes to the README.txt
=> gpkg database

graftm/unpack_sequences.py, test/test_guess_sequence_type.py
=> accept lower case input sequences

graftm/create.py, graftm/graftm_package.py, test/test_create.py
Ah biology.. there's always some exception. Before this pplacer croaked.
=> create: remove strange characters like selenocysteine (U) from alignments

graftm/taxonomy_extractor.py, test/test_taxonomy_extractor.py
solves some of Caitlin's problems, but not all.
=> create: don't read bootstraps as taxonomy in annotated trees

setup.py
same as before rebased to the new master, is this ok?
=> actually run the tests with setup.py test

graftm/housekeeping.py, graftm/reannotator.py, graftm/rerooter.py, graftm/run.py, test/test_create.py, test/test_reroot.py
not for merging - Working on one of Caitlins bugs
=> catch bady placed root and use alternative re-rooting method.

bin/graftM, graftm/hmmer.py, graftm/run.py, test/test_graft.py
The default 95bp trimming seems quite stringent to me, for matching reads. Have you done any science tuning this parameter?
=> Filter minimum update

graftm/run.py
input_taxonomy isn't necessarily defined at this point
=> fix debug msg error

bin/graftM
In relation to issue 163 (https://github.com/geronimp/graftM/issues/163)
Modified help message for graftM graft --reverse flag
- J
=> Change graftM graft --reverse help to be less conservative

bin/graftM, graftm/external_program_suite.py
Technically these are unrelated commits, but both came up in communication with someone trying to use graftm.
=> Help update

graftm/classify.py, graftm/pplacer.py
doesn't seem to be used, so I deleted it..
=> classify: assignPlacement: remove unused 'type' parameter

graftm/create.py
=> create: Actually use '10 sequences' file when testing

graftm/graftm_package.py, test/test_graftm_package.py
=> graftm_package: add is_protein_package method

graftm/create.py, graftm/hmmer.py
=> Leftover tempfiles

test/test_graft.py
Hey,
This isn't for merging, it needs more work - this is just proof of fail, but I don't have time right now. Wanna give it a go?
=> add failing test for input sequence with gaps

README.md, bin/graftM, graftm/run.py
Hey @geronimp simple little thing to help ease updating of diamond DBs when the diamond db structure changes. OK to merge?
=> update: Add option to regenerate diamond databases.

bin/graftM, graftm/run.py
Forgot to add the actual flag for create --no-tree.
Is there anywhere else I need to add it?
=> add create no-tree flags

graftm.yml
Replace pip install of bird tool utils with conda version
=> Update conda env yaml
